# scripts/pollinations_orchestrator.py

import os
import requests
from urllib.parse import quote
import pollinations as pollinations_sdk
from PIL import Image
import logging
import time
import asyncio

logger = logging.getLogger(__name__)

def generate_pollinations_video_url(prompt: str) -> str:
    """
    Generates a Pollinations AI video URL based on a descriptive prompt.

    Args:
        prompt (str): The descriptive prompt generated by Gemini AI.

    Returns:
        str: The complete Pollinations AI video URL.
    """
    base_url = "https://pollinations.ai/p/"
    encoded_prompt = quote(prompt)
    return f"{base_url}{encoded_prompt}"

def call_pollinations_for_image(prompt: str, output_dir: str, filename: str) -> str:
    """
    Calls Pollinations AI to generate an image and saves it to the specified directory.

    Includes retry logic with exponential backoff for robustness.

    Args:
        prompt (str): The prompt to send to Pollinations AI.
        output_dir (str): The directory to save the generated image.
        filename (str): The filename for the generated image.

    Returns:
        str: The path to the saved image if successful, an empty string otherwise.
    """
    retries = 3
    for i in range(retries):
        try:
            logger.info(f"Attempt {i+1}/{retries}: Calling Pollinations AI for prompt: {prompt}")
            model = pollinations_sdk.Image()
            image_pil = asyncio.run(model.Async(prompt))
            image_path = os.path.join(output_dir, filename)
            image_pil.save(image_path)
            logger.info(f"Image generated and saved to {image_path}")
            return image_path
        except Exception as e:
            logger.error(f"Error generating image with Pollinations AI (attempt {i+1}/{retries}): {e}")
            if i < retries - 1:
                time.sleep(2 ** i)  # Exponential backoff
    logger.error(f"Failed to generate image after {retries} attempts for prompt: {prompt}")
    return ""

def log_response(logs_dir: str, year: int, status: str, message: str):
    """
    Logs the Pollinations AI response status and message to a file.

    Args:
        logs_dir (str): The directory where logs are stored.
        year (int): The year associated with the response.
        status (str): The status of the Pollinations AI response.
        message (str): The message from the Pollinations AI response.
    """
    log_filename = os.path.join(logs_dir, f"response_{year}.txt")
    with open(log_filename, "a") as f:
        f.write(f"Status: {status}\n")
        f.write(f"Message: {message}\n\n")

def orchestrate_pollinations_predictions(
    initial_image_path: str,
    location_name: str,
    input_year: int,
    target_year: int,
    interval: int,
    predictions_dir: str,
    logs_dir: str
) -> list[str]:
    """
    Orchestrates iterative calls to Pollinations AI to predict future satellite images.

    Args:
        initial_image_path (str): Path to the initial satellite image.
        location_name (str): Name of the location for the satellite images.
        input_year (int): The year of the initial image.
        target_year (int): The target year for predictions.
        interval (int): The interval in years for generating intermediate images.
        predictions_dir (str): Directory to save predicted images.
        logs_dir (str): Directory to save logs.

    Returns:
        list[str]: A list of paths to all generated images (including the initial image).
    """
    generated_image_paths = [initial_image_path]
    current_year = input_year
    current_image_path = initial_image_path

    while current_year < target_year:
        next_year = min(current_year + interval, target_year)
        
        # Build prompt for Pollinations AI
        prompt = (
            f"Given this satellite image of {location_name} in {current_year}, "
            f"analyze past changes and generate a realistic future satellite image for {next_year}, "
            f"showing likely urban, vegetation, water, and infrastructure evolution. "
            f"Preserve geography and satellite view realism."
        )
        
        # Log the prompt
        log_prompt(logs_dir, current_year, next_year, prompt)

        # Call Pollinations AI to generate the next image
        generated_filename = f"prediction_{next_year}.png"
        new_image_path = call_pollinations_for_image(prompt, predictions_dir, generated_filename)
        
        if new_image_path:
            generated_image_paths.append(new_image_path)
            current_image_path = new_image_path
            current_year = next_year
        else:
            logger.error(f"Failed to generate image for year {next_year}. Stopping prediction.")
            break

    logger.info(f"Final generated image paths: {generated_image_paths}")
    return generated_image_paths

def log_prompt(logs_dir: str, current_year: int, next_year: int, prompt: str):
    """
    Logs the Pollinations AI prompt to a file.

    Args:
        logs_dir (str): The directory where logs are stored.
        current_year (int): The starting year of the prediction.
        next_year (int): The target year of the prediction.
        prompt (str): The prompt sent to Pollinations AI.
    """
    log_filename = os.path.join(logs_dir, f"prompt_{current_year}_to_{next_year}.txt")
    with open(log_filename, "w") as f:
        f.write(prompt)