import urllib.parse
import logging
import os

logger = logging.getLogger(__name__)

def generate_pollinations_video_url(prompt: str) -> str:
    """
    Generates a Pollinations AI video URL based on a descriptive prompt.

    Args:
        prompt (str): The descriptive prompt generated by Gemini AI.

    Returns:
        str: The complete Pollinations AI video URL.
    """
    logger.info(f"Generating Pollinations URL for prompt: {prompt}")
    encoded_prompt = urllib.parse.quote(prompt)
    # Use GEMINI_API_KEY from app.config if needed for Pollinations API directly
    # For now, Pollinations AI image generation doesn't require an explicit API key in the URL
    pollinations_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?video=true"
    logger.info(f"Generated Pollinations URL: {pollinations_url}")
    return pollinations_url